import { text as T } from './i18n.ts'
import type { Scene, SceneId, Choice, KnowledgeId } from './model.ts'
export const knowledge: Record<KnowledgeId, ReturnType<typeof T>> = {
  'light-response': T('強い白色光でロボットの走査が中断した。暗闇では走査を続けた。', 'Strong white light interrupted the robot’s scan. Darkness did not.'),
  'arm-traces': T('二本の黒い擦過痕は、旋回するロボットのアームが残す。', 'Paired black scrapes are left by the robot’s arm when it turns.'),
  'independent-power': T('旧整備系統は独立電源。青い表示は基地の主電源と連動しない。', 'The old service system has independent power. Its blue indicators do not follow base power.'),
  'launch-order': T('帰還船は「圧力固定 → 点火」。逆順では空気を排出する。', 'The ship requires pressure lock before ignition. Reversing the order vents air.'),
}
const C = (id: string, ja: string, en: string, next: SceneId, resultJa: string, resultEn: string, rest: Partial<Choice> = {}): Choice => ({ id, label: T(ja, en), next, result: T(resultJa, resultEn), ...rest })
const noisy = (next: SceneId): Choice['routes'] => [{ when: { threatMin: 2 }, next: 'encounter' }, { when: {}, next }]
export const scenes: Record<SceneId, Scene> = {
  wake: {
    id: 'wake', title: T('残った呼吸', 'The remaining breath'),
    narrative: [T('天井の継ぎ目から灰色の粉が落ちてくる。スーツの呼吸音だけは一定だ。', 'Grey dust sifts through a ceiling seam. My suit keeps a steady breathing rhythm.'), T('壁に二本の黒い擦過痕が残っている。扉の外で、金属音が三度続いて止まった。', 'Two black scrapes mark the wall. Beyond the door, metal strikes three times, then falls silent.'), T('AI：基地は致命的損傷。帰還船での脱出が必要です。扉の気密は維持されています。', 'AI: Base damage is critical. Escape aboard the return ship is required. This door still holds pressure.')],
    choices: [C('check-kit', '足元の救急ケースを開く', 'Open the emergency case at my feet', 'kit', '留め具を指で外す。ケースの中は乾いている。', 'I ease the catches open. The case is dry inside.'), C('leave-case', 'ケースを残し、扉に耳を寄せる', 'Leave the case and listen at the door', 'door', '荷物を増やさず、扉へ近づく。', 'I move to the door without adding to my load.')],
  },
  kit: {
    id: 'kit', title: T('一回分の備え', 'One reserve'),
    narrative: [T('ケースには携帯ライトと小さな酸素容器が収まっている。容器は固定帯に絡まり、外すにはしばらく手を止める必要がある。', 'A portable light and a small oxygen flask sit inside. The flask is tangled in its strap; freeing it will take time.'), T('扉の向こうで、三度の金属音が再び響く。今度は少し近い。', 'The three metallic knocks return beyond the door. They sound a little closer this time.'), T('AI：予備酸素は一回分。長い作業には呼吸用空気を消費します。', 'AI: The flask holds one refill. Extended work consumes breathing air.')],
    choices: [C('take-both', '固定帯をほどき、ライトと予備酸素を持つ', 'Untangle the strap; take light and oxygen', 'door', '帯をほどく間、ファンが空気を送り続ける。二つをスーツへ固定する。', 'The fan keeps feeding air while I work. I secure both to my suit.', { effect: { gain: ['light', 'flask'], oxygen: 1, threat: 1 } }), C('take-light', 'すぐ取れるライトだけを持つ', 'Take only the loose light', 'door', 'ライトを抜き取り、容器には触れない。', 'I take the light and leave the flask secured.', { effect: { gain: ['light'] } })],
  },
  door: {
    id: 'door', title: T('音の間隔', 'Between the sounds'),
    narrative: [T('扉の隙間を細い影が横切る。赤い走査光が床をなぞり、記録端末の白い画面の前で折り返した。', 'A thin shadow crosses the door gap. A red scan traces the floor, turning back at a record terminal’s white screen.'), T('金属音が三度続いて止まる。隙間からは、端末の点滅と青く灯る古い整備表示が見える。', 'Metal knocks three times and stops. Through the gap I can see the terminal flicker and an old service indicator glowing blue.'), T('AI：移動する機械反応。今、扉を大きく開くのは危険です。', 'AI: Moving machine signature. Opening the door wide now is dangerous.')],
    choices: [C('read-terminal', '走査光が引くのを待ち、端末へ手を伸ばす', 'Wait for the scan to withdraw; reach the terminal', 'records', '光が消える間に体を低くして滑り込む。', 'I slip through low as the light withdraws.', { effect: { threat: 1 } }), C('service-hatch', '青い表示の下の点検蓋を静かに外す', 'Quietly lift the hatch below the blue indicator', 'service', '蓋は手で外れる。中のファンは途切れず回っている。', 'The hatch lifts by hand. Its fan keeps turning steadily.'), C('force-door', '危険を承知で扉を押し開ける', 'Accept the danger and force the door open', 'encounter', '扉が床をこする。赤い光が私の胸で止まった。', 'The door scrapes the floor. Red light stops on my chest.', { effect: { threat: 2 } })],
  },
  records: {
    id: 'records', title: T('最後の記録', 'The last record'),
    narrative: [T('画面には整備映像と帰還船の操作記録が並んでいる。映像の最初では、白い作業灯を向けられたロボットが走査を止めている。', 'Maintenance footage sits beside a ship procedure log. In the opening frame, the robot stops scanning under a white work lamp.'), T('続きの読込みバーは遅い。端末の冷却ファンが、沈黙の中で回転を上げる。', 'The remaining footage loads slowly. The terminal’s cooling fan grows louder in the silence.'), T('AI：全記録の再生には時間が必要です。表示中の要約だけなら、すぐ読めます。', 'AI: Full playback takes time. The visible summary can be read immediately.')],
    choices: [C('full-record', '追跡映像と発進記録を最後まで読む', 'Read the pursuit footage and launch log in full', 'playback', '映像を止めずに見る。ファンの音に、金属音が重なり始める。', 'I let the footage run. Metallic sounds join the fan.', { effect: { learn: ['light-response', 'arm-traces', 'launch-order'], oxygen: 1, threat: 1 } }), C('summary', '白い作業灯の記録だけ読み、離れる', 'Read only the white-lamp summary, then leave', 'seal', '要約には「強い白色光で走査中断。消灯では無効」とある。', 'The summary reads: “Strong white light interrupts scanning. Darkness does not.”', { effect: { learn: ['light-response'] } }), C('skip-record', '記録を読まず、端末の音から離れる', 'Leave the noisy terminal without reading', 'seal', '点滅する画面を背にする。続きを確かめる余裕はない。', 'I turn away from the flickering screen, leaving the rest unread.', { effect: { threat: -1 } })],
  },
  playback: {
    id: 'playback', title: T('旋回の跡', 'What the turn leaves'),
    narrative: [T('映像のロボットが旋回するたび、壁にアームが触れ、二本の黒い筋を残す。目覚めたときの壁にも、同じ筋があった。', 'Each time the robot turns in the footage, its arm brushes the wall, leaving paired black lines. The wall where I woke had the same marks.'), T('発進記録には「圧力固定後、点火」とある。逆順の試験では、船内の空気が排出されていた。', 'The launch log says “Lock pressure, then ignite.” In a reversed test, cabin air was vented.'), T('机の下で簡易デコイの試験ランプが点いている。引き抜けば音が鳴りそうだ。', 'A test lamp glows on a simple decoy beneath the desk. Pulling it free looks likely to make noise.')],
    choices: [C('take-decoy', '音を承知でデコイを引き抜く', 'Pull the decoy free despite the noise', 'seal', '試験音が三度響く。デコイを握り、端末を離れる。', 'Three test knocks ring out. I take the decoy and leave.', { effect: { gain: ['decoy'], threat: 1 }, routes: noisy('seal') }), C('leave-decoy', 'デコイを残し、静かに離れる', 'Leave the decoy and withdraw quietly', 'seal', '机に触れず、ファンの音から離れる。', 'I leave the desk untouched and move away from the fan.', { effect: { threat: -1 } })],
  },
  service: {
    id: 'service', title: T('消えない青', 'Blue that stays lit'),
    narrative: [T('頭上の非常灯が一斉に暗くなる。それでも、点検蓋の内側の青い表示とファンは止まらない。', 'The emergency lamps overhead dim together. The blue indicator inside the hatch and its fan keep running.'), T('銘板には「旧整備系統・独立電源」とある。奥には工具台と、細い空気配管が見える。', 'The plate reads “Legacy service system — independent supply.” I can see a tool bench and a narrow air line beyond.'), T('AI：主電源とは別の系統です。基地全体を復旧できる設備ではありません。', 'AI: This supply is independent of main power. It cannot restore the whole base.')],
    choices: [C('inspect-bench', '青い配管に沿って工具台を調べる', 'Follow the blue line and inspect the bench', 'workbench', '銘板の内容を覚え、工具台へ身を寄せる。', 'I remember the plate and ease up to the bench.', { effect: { learn: ['independent-power'] } }), C('crawl-through', '立ち止まらず、狭い開口を抜ける', 'Keep moving through the narrow opening', 'seal', '縁で左腕を打つ。音を立てずに抜けるが、腕に力が入りにくい。', 'My left arm hits the rim. I get through quietly, but the arm feels weak.', { effect: { body: 'injured' } })],
  },
  workbench: {
    id: 'workbench', title: T('外すか、引くか', 'Unfasten or pull'),
    narrative: [T('工具は金属帯で固定され、帯のネジは指でも回るが、何本もある。帯の裏に試験札が挟まっているが、文字は隠れている。', 'A metal strap holds the tools; its several screws can be turned by hand. A test tag is tucked behind the strap, its text obscured.'), T('横の箱には「音響試験」と書かれ、簡易デコイが差し込まれている。箱のスイッチは入ったままだ。', 'A box marked “Acoustic test” holds a simple decoy. Its switch is still on.'), T('配管から冷たい空気が漏れている。ここに長く留まれば、呼吸用空気も減っていく。', 'Cold air leaks from the pipe. Spending time here will use up my breathing air too.')],
    choices: [C('unscrew-tools', '試験札を読み、ネジを外して工具を持つ', 'Read the test tag and unfasten the tools', 'seal', '札には「強い白色光で走査中断。消灯では無効」とある。帯を外し、音を立てないよう工具を包む。', 'The tag reads: “Strong white light interrupts scanning. Darkness does not.” I undo the strap and wrap the tools to keep them from clinking.', { effect: { gain: ['tools'], oxygen: 1, learn: ['light-response'] } }), C('pull-decoy', '試験箱からデコイを引き抜く', 'Pull the decoy out of its test box', 'seal', '試験音が響く。箱を残し、デコイだけを持つ。', 'The test sound rings out. I leave the box and take the decoy.', { effect: { gain: ['decoy'], threat: 1 }, routes: noisy('seal') }), C('leave-bench', '道具に触れず、空気漏れから離れる', 'Leave the tools and move away from the leak', 'seal', '工具台を離れる。青い表示の光が背中へ回る。', 'I leave the bench. The blue glow falls behind me.')],
  },
  seal: {
    id: 'seal', title: T('袖口の振動', 'A vibration at the cuff'),
    narrative: [T('袖口が細かく震え、空気の細い音が続いている。布の下にある締め輪がずれている。', 'My cuff trembles with a thin hiss. The retaining ring beneath the fabric has slipped.'), T('先の扉は帰還船の案内灯で縁取られている。締め輪を扱っている間にも、遠くの金属音が何度か響く。', 'A ship guide lamp outlines the door ahead. Metal sounds ring out in the distance while I examine the ring.'), T('AI：スーツに微小漏れ。手で押さえれば進めますが、走行時には酸素が減ります。修正には時間が必要です。', 'AI: Minor suit leak. Holding the ring permits walking, but running will cost oxygen. Correction takes time.')],
    additions: [{ when: { body: 'injured' }, text: T('左腕が締め輪を押すたびに痛む。素手で直すには、力が足りない。', 'My left arm hurts against the ring. I cannot repair it by hand with this grip.') }],
    choices: [C('tool-seal', '工具で締め輪を直す', 'Correct the ring with tools', 'marks', '工具を当てる。空気の音が止まるまで、慎重に輪を戻す。', 'I work the ring back carefully until the hiss stops.', { when: { items: ['tools'] }, effect: { oxygen: 1, once: 'sealed' } }), C('hand-seal', '腕に力を込め、締め輪を戻す', 'Force the ring back by hand', 'marks', '輪が戻る。力を込めた左腕に痛みが残る。', 'The ring seats. The effort leaves my left arm aching.', { when: { body: 'normal' }, effect: { body: 'injured', once: 'sealed' } }), C('hold-seal', '袖口を押さえ、立ち止まらず進む', 'Hold the cuff and keep walking', 'marks', '袖口を押さえると音が弱まる。走らずに進む。', 'Pressure on the cuff quiets the hiss. I walk without running.')],
  },
  marks: {
    id: 'marks', title: T('二本の黒い筋', 'Two black lines'),
    narrative: [T('扉の右縁に、二本の黒い擦過痕が残っている。奥の床には赤い光がゆっくり横切る。', 'Two black scrapes mark the right edge of the door. Red light drifts across the floor beyond.'), T('左側には低い配管の陰がある。床の金属板は浮き、踏めば響きそうだ。', 'Low pipes cast a shadow on the left. A loose floor plate looks ready to ring under a foot.')],
    additions: [{ when: { knowledge: ['arm-traces'] }, text: T('あの映像と同じ痕だ。右側でロボットのアームが旋回した。配管の陰なら、アームの高さより低い。', 'The marks match the footage. The robot’s arm turned on the right. The pipe shadow lies below the arm’s height.') }, { when: { knowledge: ['light-response'], items: ['light'] }, text: T('赤い光は走査だ。白い作業灯で止まった映像を思い出し、ライトの照射切替に指を置く。', 'That red light is a scan. I remember it stopping under the white lamp and touch my light’s beam selector.') }],
    choices: [C('trace-shadow', '擦過痕からアームの高さを読み、配管の陰を使う', 'Use the scrapes to judge arm height; slip below the pipes', 'relay', '低い姿勢のまま、赤い光が通り過ぎるのを見送る。', 'I stay low and let the red light pass.', { when: { knowledge: ['arm-traces'] }, effect: { threat: -1 } }), C('flood-scan', '走査へ強い白色光を向ける', 'Aim a strong white beam into the scan', 'relay', '白い光を浴びた走査光が止まる。残った明かりで扉を抜ける。', 'The scan freezes in the white beam. I use the remaining light to pass through.', { when: { knowledge: ['light-response'], items: ['light'] }, effect: { threat: -1 } }), C('wait-scan', '赤い光が遠のくまで身を伏せる', 'Lie low until the red light moves away', 'relay', '光が引くまで待つ。立ち上がると、呼吸のファン音が妙に耳につく。', 'I wait for the light to recede. When I rise, the breathing fan sounds unusually loud.', { effect: { oxygen: 1, threat: -1 } }), C('step-plate', '待たずに金属板を踏み越える', 'Cross the loose plate without waiting', 'relay', '板が足元で鳴る。静けさが途切れる。', 'The plate rings under my foot. The silence breaks.', { effect: { threat: 1 }, routes: noisy('relay') })],
  },
  relay: {
    id: 'relay', title: T('消灯した装置', 'A dark machine'),
    narrative: [T('帰還船への昇降装置は暗い。隣の古い操作箱だけが、青く灯っている。', 'The lift toward the ship is dark. Only an old control box beside it glows blue.'), T('手動レバーには重いばねが掛かっている。主電源の再接続ボタンには「試験警報」と書かれている。', 'A heavy spring holds the manual lever. The main-power reconnect button is marked “Test alarm.”')],
    additions: [{ when: { oxygenMin: 2 }, text: T('吸い込んだ空気が薄い。警告表示が点滅し、もう長い作業には耐えられない。', 'The air feels thin. A warning blinks; I cannot afford more prolonged work.') }, { when: { knowledge: ['independent-power'] }, text: T('点検蓋で見た青と同じだ。旧整備系統の電源なら、主電源を起こさず動かせる。', 'It is the same blue as inside the hatch. The legacy supply can run this without waking main power.') }, { when: { threatMax: 0 }, text: T('遠くで何かが動いている。音の間には、まだ長い静けさがある。', 'Something moves far away. Long silences still separate the sounds.') }, { when: { threatMin: 1, threatMax: 1 }, text: T('金属音が何度も近づいてくる。レバーを握る指を止め、耳を澄ます。', 'Metal sounds draw closer again and again. I still my fingers on the lever and listen.') }, { when: { threatMin: 2 }, text: T('扉の向こうで駆動音が止まった。隙間を赤い光がなぞっている。', 'A motor stops beyond the door. Red light traces the gap.') }, { when: { oxygenMax: 0 }, text: T('胸の中へ、一定の速さで空気が届く。', 'Air reaches my chest in an even rhythm.') }, { when: { oxygenMin: 1, oxygenMax: 1 }, text: T('装置の静けさの中で、ファンの回転音が目立つ。', 'In the machine’s silence, the breathing fan stands out.') }],
    choices: [C('blue-power', '青い操作箱で独立電源をつなぐ', 'Connect the independent supply at the blue box', 'airlock', '青い表示だけが明るくなる。装置は静かに持ち上がる。', 'Only the blue indicators brighten. The lift rises quietly.', { when: { knowledge: ['independent-power'] } }), C('manual-lift', '重いレバーを手で押し切る', 'Push the heavy lever through by hand', 'airlock', 'ばねを押し切る。腕に痛みが走るが、装置は動く。', 'I force the spring back. Pain runs through my arm, but the lift moves.', { when: { body: 'normal' }, effect: { body: 'injured' } }), C('tool-lift', '工具を支点にしてレバーを動かす', 'Use a tool as leverage on the handle', 'airlock', '工具を挟み、ゆっくり力を掛ける。呼吸を重ねるうちに装置が動く。', 'I brace a tool and apply pressure slowly. After several breaths, the lift moves.', { when: { items: ['tools'] }, effect: { oxygen: 1 } }), C('alarm-power', '警報を承知で主電源を再接続する', 'Reconnect main power despite the alarm', 'airlock', '警報が鳴る。装置の照明が戻る。', 'The alarm rings. The lift lights return.', { effect: { threat: 1 }, routes: noisy('airlock') }), C('wait-relay', '物陰で機械音が離れるのを待つ', 'Wait in cover for the machine to move away', 'relay', '三度の音が、少し遠くで繰り返される。待つ間にも空気は減る。', 'The triple sound repeats farther away. Waiting still uses air.', { when: { unused: 'relay-wait' }, effect: { threat: -1, oxygen: 1, once: 'relay-wait' } })],
  },
  encounter: {
    id: 'encounter', title: T('走査光の下で', 'Under the scan'),
    narrative: [T('赤い光が胸をなぞる。扉に触れたアームが二本の黒い筋を引き、床の板がきしむ。', 'Red light traces my chest. An arm draws two black lines across the door; the floor plate creaks.'), T('低い機材棚の隙間と、白い非常灯のスイッチが見える。スイッチのカバーには、工具用のネジがある。', 'I can see a gap beneath a low equipment shelf and a white emergency-lamp switch. A tool screw holds its cover.'), T('AI：危険度、高。走行は空気を消費します。暗闇でも走査は継続します。', 'AI: Danger high. Running consumes air. Scanning continues in darkness.')],
    choices: [C('use-decoy', 'デコイを投げ、音と逆へ身を滑らせる', 'Throw the decoy; slip away from its sound', 'refuge', '三度の音へ走査光が折れる。焼けたデコイを残す。', 'The scan turns toward the triple knock. I leave the burned-out decoy behind.', { when: { items: ['decoy'] }, effect: { consume: ['decoy'], threat: -2 } }), C('emergency-light', 'カバーを外し、白い非常灯を起動する', 'Remove the cover and switch on the white emergency lamp', 'refuge', '工具でカバーを外す。白い光の中で走査が止まり、その間に退く。', 'I remove the cover with a tool. The scan stops in white light, letting me withdraw.', { when: { items: ['tools'], knowledge: ['light-response'] }, effect: { oxygen: 1, threat: -1 } }), C('use-light', 'ライトを強い照射に切り替える', 'Switch my light to its flood beam', 'refuge', '白い光がアームを照らす。走査が止まった間に身を引く。', 'White light catches the arm. I withdraw while its scan is stopped.', { when: { items: ['light'], knowledge: ['light-response'] }, effect: { threat: -1 } }), C('run', '腕を犠牲に、機材棚の隙間へ飛び込む', 'Throw myself under the shelf at the cost of my arm', 'refuge', '左腕を棚へ打ちつける。呼吸が乱れるが、アームは届かない。', 'My left arm strikes the shelf. My breath breaks, but the arm cannot reach me.', { when: { body: 'normal', oxygenMax: 1 }, effect: { body: 'injured', oxygen: 1, threat: -1 }, routes: [{ when: { unused: 'sealed' }, next: 'refuge', effect: { oxygen: 2 }, result: T('棚へ飛び込む衝撃で袖口が開く。アームは届かないが、空気が一気に抜ける。', 'The impact opens my loose cuff. The arm cannot reach me, but air rushes out.') }] }), C('dark-hide', '照明を消し、その場で動きを止める', 'Turn off the light and freeze in place', 'robot-over', '暗くしても赤い光は消えない。アームが視界をふさぐ。', 'The red light remains in the darkness. The arm fills my view.')],
  },
  refuge: {
    id: 'refuge', title: T('届かない隙間', 'Out of reach'),
    narrative: [T('棚の向こうで金属音が三度響き、やがて遠くなる。低い点検口の先に、帰還船の気密室が見える。', 'Metal knocks three times beyond the shelf, then recedes. Through a low service opening I can see the ship’s pressure chamber.'), T('ここでは立ち上がれない。待つより、呼吸を整えながら這って抜けた方がよさそうだ。', 'There is no room to stand. Crawling out while steadying my breathing seems better than waiting.')],
    additions: [{ when: { body: 'injured' }, text: T('左腕をかばい、肘ではなく肩で体を支える。', 'I protect my left arm, supporting myself on my shoulder instead.') }],
    choices: [C('close-refuge', '時間をかけて点検口を閉じ、音を遮る', 'Take time to close the service hatch and muffle the noise', 'airlock', '蓋を静かに引く。音が弱まるまで、何度か呼吸する。', 'I ease the hatch shut. Several breaths pass before the noise fades.', { effect: { oxygen: 1, threat: -1 } }), C('crawl-out', '呼吸を整え、点検口をくぐる', 'Steady my breathing and crawl through', 'airlock', '肩を低くして隙間を抜ける。気密室の灯りが視界に広がる。', 'I lower my shoulder and squeeze through. Chamber lights fill my view.'), C('refuge-refill', '予備酸素を使ってから点検口をくぐる', 'Refill my oxygen before crawling through', 'airlock', '容器を接続する。落ち着いた呼吸とともに、点検口を抜ける。', 'I connect the flask, then crawl through with an even breath.', { when: { items: ['flask'] }, effect: { refill: true, consume: ['flask'] } })],
  },
  airlock: {
    id: 'airlock', title: T('空気を守る扉', 'A door that holds air'),
    narrative: [T('帰還船の入口は、気密室のガラス越しに見える。閉鎖ボタンの横に「自動均圧」と「手動弁」の二つの表示がある。', 'The ship entrance is visible through the chamber glass. Beside the close button are labels for “Automatic equalisation” and “Manual valve.”'), T('自動均圧のランプはゆっくり点滅している。手動弁はスーツの手袋では握れないほど細い。', 'The automatic lamp blinks slowly. The manual valve is too narrow to grip with suit gloves.'), T('AI：自動均圧には待機が必要です。開いたまま非常開放すると呼吸用空気を失います。', 'AI: Automatic equalisation requires waiting. Emergency release while open will cost breathing air.')],
    additions: [{ when: { oxygenMin: 2 }, text: T('吸い込む空気が薄い。ここでさらに待てば、最後の空気を使ってしまう。', 'The air I draw is thin. Waiting here will use the last of it.') }, { when: { oxygenMax: 0 }, text: T('ガラスに呼気が曇り、すぐ消える。まだ落ち着いて待てる。', 'My breath briefly fogs the glass. I can still wait calmly.') }, { when: { oxygenMin: 1, oxygenMax: 1 }, text: T('吸気のたび、ファンが長く回る。ランプの点滅が遅く感じられる。', 'The fan runs longer on each breath. The blinking lamp feels slow.') }],
    choices: [C('manual-valve', '工具で手動弁を回し、空気を閉じ込める', 'Turn the manual valve with tools and trap the air', 'ship', '工具が弁をつかむ。気流が止まってから扉を開く。', 'The tool grips the valve. I open the door after the airflow stops.', { when: { items: ['tools'] }, effect: { threat: 1 }, routes: noisy('ship') }), C('equalise', '扉を閉め、自動均圧を待つ', 'Close the door and wait for equalisation', 'ship', '閉まる扉を見届ける。呼吸を重ね、点滅が止まるのを待つ。', 'I watch the door close, breathing through the wait until the lamp steadies.', { effect: { oxygen: 1, threat: -1 } }), C('airlock-refill', '予備酸素を使い、余裕を作る', 'Use reserve oxygen to make time', 'airlock', '容器を接続する。吸い込む空気が戻り、残った容器は空になる。', 'I connect the flask. Air returns; the flask empties.', { when: { items: ['flask'] }, effect: { consume: ['flask'], refill: true } }), C('vent-door', '空気を失う危険を承知で非常開放する', 'Use emergency release despite losing air', 'ship', '空気が扉へ引かれる。スーツの警告音が短く鳴る。', 'Air pulls toward the door. My suit gives a short warning.', { effect: { oxygen: 1, threat: 1 }, routes: noisy('ship') })],
  },
  ship: {
    id: 'ship', title: T('二つのスイッチ', 'Two switches'),
    narrative: [T('帰還船の座席へ体を沈める。操作盤には「圧力固定」と「点火」のスイッチが並んでいる。', 'I sink into the ship’s seat. “Pressure lock” and “Ignition” sit side by side on the panel.'), T('透明カバーの内側に小さな手順票がある。読もうとすれば、まずカバーを外さなければならない。', 'A small procedure card sits inside the transparent cover. Reading it requires removing the cover first.'), T('AI：航路設定は有効。圧力固定は未実行です。', 'AI: Flight plan is valid. Pressure lock has not been engaged.')],
    additions: [{ when: { oxygenMin: 2 }, text: T('警告表示が点滅している。カバーを外して読む時間にも、空気が必要だ。', 'A warning blinks. Removing and reading the cover will still cost air.') }, { when: { knowledge: ['launch-order'] }, text: T('端末で読んだ順序を思い出す。空気を排出した試験と、同じ二つのスイッチだ。', 'I remember the order in the terminal log. These are the same two switches from the venting test.') }],
    choices: [C('known-launch', '記録の通り、圧力を固定してから点火する', 'Follow the record: lock pressure, then ignite', 'clear', '固定表示を確かめ、点火する。座席に静かな振動が伝わる。', 'I verify the lock indicator and ignite. A quiet vibration reaches the seat.', { when: { knowledge: ['launch-order'] } }), C('read-card', 'カバーを外し、手順票を読む', 'Remove the cover and read the procedure card', 'checklist', 'カバーを外す間、ファンが回る。票には発進順序が図で示されている。', 'The fan runs while I remove the cover. The card diagrams the launch order.', { effect: { oxygen: 1, learn: ['launch-order'] }, routes: [{ when: { items: ['tools'] }, next: 'checklist', effect: { oxygen: 0 }, result: T('工具ですぐにカバーを外す。票の発進順序が読める。', 'A tool lifts the cover immediately. I can read the launch order on the card.') }] }), C('ignite-first', '空気排出の危険を承知で、先に点火する', 'Ignite first despite the risk of venting air', 'oxygen-over', '排気弁が開く。座席に体を固定する前に、空気が引かれていく。', 'The vent valve opens. Air drains away before I can secure myself.')],
  },
  checklist: {
    id: 'checklist', title: T('固定、そして点火', 'Lock, then ignite'),
    narrative: [T('票には「圧力固定 → 点火」とある。逆順では空気を排出する、と赤い線で囲まれている。', 'The card reads “Pressure lock → Ignition.” A red box warns that reversing the order vents air.'), T('帰還船の窓には基地の非常灯が映っている。今は、その明かりから離れる順序が分かる。', 'Base emergency lamps reflect in the window. Now I know the sequence that will take me away from them.')],
    choices: [C('card-launch', '手順票の通りに圧力を固定し、点火する', 'Lock pressure and ignite as the card instructs', 'clear', '固定表示が点く。点火すると、窓の基地がゆっくり下がる。', 'The lock indicator lights. On ignition, the base sinks slowly below the window.'), C('flask-launch', '予備酸素を使い、呼吸を整えて発進する', 'Refill, steady my breath, then launch', 'clear', '容器を空にし、圧力を固定する。点火の振動を、一定の呼吸で迎える。', 'I empty the flask and lock pressure. An even breath meets the vibration of ignition.', { when: { items: ['flask'] }, effect: { consume: ['flask'], refill: true } })],
  },
  clear: { id: 'clear', title: T('EXIT SEQUENCE / GAME CLEAR', 'EXIT SEQUENCE / GAME CLEAR'), narrative: [T('月面の灯りが一つの点へ縮んでいく。スーツではなく、船内の空気を吸う。', 'The lights on the lunar surface shrink to a point. I breathe cabin air instead of suit air.'), T('AI：月面離脱を確認。地球への帰還航路へ移行します。', 'AI: Lunar departure confirmed. Transferring to the Earth return trajectory.')], choices: [], ending: 'clear' },
  'robot-over': { id: 'robot-over', title: T('GAME OVER / 途切れた走査', 'GAME OVER / The final scan'), narrative: [T('赤い光が視界を満たす。スーツに響く金属音を最後に、表示が消える。', 'Red light fills my view. A metallic strike passes through the suit, and the display goes dark.'), T('AI：退避不能。', 'AI: Escape unavailable.')], choices: [], ending: 'over' },
  'oxygen-over': { id: 'oxygen-over', title: T('GAME OVER / 最後の空気', 'GAME OVER / The last air'), narrative: [T('吸い込もうとしても、胸に空気が届かない。警告表示だけが視界の端で点滅している。', 'I try to breathe, but no air reaches my chest. Only a warning keeps blinking at the edge of my view.'), T('AI：呼吸用酸素が尽きました。', 'AI: Breathing oxygen exhausted.')], choices: [], ending: 'over' },
}
