import { text as t } from './i18n.ts';
import { equipment } from './items.ts';
import type { Choice, Clues, Effect, ProblemId, Scene, SceneId } from './model.ts';
export const clues: Record<ProblemId, Clues> = {
    door: { initial: t("電源ランプは緑だ。ボタンを押すとモーターが鳴り、扉は少し開いて止まる。左右の圧力表示は「高い」「低い」。", "The power lamp is green. I press the button. The motor runs, but the door moves a little and stops. The air pressure labels read HIGH and LOW."), inspect: t("動く歯車が見える。故障灯は消えている。扉のすき間から、低い圧力の側へ空気が流れる。", "The gears turn. The fault lamp is off. Air flows through the gap toward the side marked LOW."), deeper: t("透明な点検窓に、扉を押す力の矢印が出る。高い圧力の側から大きな矢印。低い側から小さな矢印。扉は押し戻されている。盤には「均圧：左右の空気圧を近づける」。", "A clear inspection window shows arrows for the forces on the door. A big arrow from the HIGH side. A small one from the LOW side. The door is being pushed back. The panel reads: EQUALIZE \u2014 bring both air pressures closer."), hints: [t("AI：モーターは動き、故障灯は消えています。まず左右の表示と、すき間の空気を見てください。ボタンの根性試しではありません。", "AI: The motor runs and the fault lamp is off. Look at both pressure labels and the air in the gap. This is not a test of the button\u2019s courage."), t("AI：点検窓の矢印を見てください。高い圧力の空気が強く押し、扉を戻しています。モーターの故障ではありません。", "AI: Look at the arrows in the inspection window. The high-pressure air pushes harder and holds the door back. The motor is not broken."), t("AI：左右の空気圧の違いが原因です。「均圧」で圧力を近づければ、扉を押し戻す力が小さくなります。その後、開閉ボタンを押せます。", "AI: The different air pressures are the cause. EQUALIZE brings them closer and reduces the force holding the door back. Then you can press OPEN.")] },
    valve: { initial: t("通路のバルブは冷たい。レバーを押しても動かない。カバーの外からは、何につかえているか見えない。", "The passage valve feels cold. Its lever will not move. The cover hides whatever is blocking it."), inspect: t("カバーを開ける。バルブ軸そのものに白い氷が張り付いている。レバーをそっと押すと、軸の突起が氷に当たって止まる。", "I open the cover. White ice clings to the valve shaft itself. I gently push the lever. A ridge on the shaft hits the ice and stops."), deeper: t("氷は軸と枠の間をふさいでいる。曲がった部品は見えない。隣の棚に点検ヒーターと工具。ヒーターの札には「冷えた部品を温める」。", "Ice fills the space between the shaft and frame. No part looks bent. An inspection heater and tools sit nearby. The heater label says: warms cold parts."), hints: [t("AI：カバーを開けて軸を見ましょう。冷たいというだけでは、原因は決められません。", "AI: Open the cover and look at the shaft. Cold alone does not prove the cause."), t("AI：軸の突起が、見えている氷にぶつかっています。氷が動きを止めています。力不足ではありません。", "AI: The ridge hits the ice you can see. That ice blocks the movement. You are not too weak."), t("AI：原因は軸に張り付いた氷です。温めれば氷は水になります。棚の点検ヒーターを軸に当て、氷が消えてからレバーを押してください。", "AI: Ice stuck to the shaft is the cause. Warmth turns ice into water. Put the inspection heater on the shaft. Once the ice is gone, push the lever.")] },
    power: { initial: t("帰還設備を起動すると、電力計が上限まで振れる。ブレーカーが落ちた。表示は「OVERLOAD」。船の空気充填機と貨物リフトが同時に動いていた。", "I start the return equipment. The power meter hits its limit. The breaker trips. The display reads OVERLOAD. The cabin air pump and cargo lift were running together."), inspect: t("盤の説明は「OVERLOAD：同時に使う電力が多すぎます」。故障灯は消えている。二つの装置を一台ずつ試すと、針は上限より下で止まる。", "The panel explains: OVERLOAD \u2014 too much power used at once. The fault lamp is off. Testing each machine alone leaves the needle below the limit."), deeper: t("二台同時だと針が上限を越え、電気が切れる。一台ずつなら切れない。空気充填は帰還に必要。貨物リフトは空で、今は使わなくてもよい。盤には個別停止と順番運転がある。", "Together, the machines push the meter past the limit and cut the power. Alone, each keeps running. The air pump is needed for the journey. The cargo lift is empty and optional. The panel has separate stop controls and a run-in-order setting."), hints: [t("AI：OVERLOADの説明と電力計を見てください。故障灯は点いていません。二台が動いていたことも確認できます。", "AI: Read the OVERLOAD explanation and check the meter. The fault lamp is off. You can also see that two machines were running."), t("AI：一台ずつなら上限以下。二台同時なら上限を越えます。同時に使いすぎているのが原因です。", "AI: Each machine alone stays below the limit. Together they go over it. Using too much at once is the cause."), t("AI：使える電力には限りがあります。空の貨物リフトを止めて空気充填機だけ動かすか、二台を順番に動かしてください。どちらも同時の使いすぎを避けられます。", "AI: The power supply has a limit. Stop the empty cargo lift and run only the air pump, or run the two machines in order. Either avoids using too much at once.")] },
};
const a = (id: string, label: ReturnType<typeof t>, next: SceneId, result: ReturnType<typeof t>, effect?: Effect): Choice => ({ id, label, next, result, effect });
const hint = (problem: ProblemId, next: SceneId): Choice => a(problem + '-hint-' + next, t('AIにヒントを聞く', 'Ask AI for a hint'), next, t('', ''), { problem, hint: true });
const list: Scene[] = [
    { id: "wake", title: t("帰還船へ", "To the return ship"), narrative: [t("遠くでロボットの足音がする。帰還船まで、三つの設備が止まっている。「今日に限って、全部ご機嫌ななめか」", "A robot\u2019s footsteps echo far away. Three stopped machines stand between me and the return ship. \u201cEveryone picked today to be difficult.\u201d"), t("AI：まず、何が起きているか確かめましょう。ヒントは何度聞いても安全です。", "AI: First, find out what is happening. Asking for hints is always safe.")], choices: [a("begin", t("最初の扉へ", "Go to the first door"), "door", t("足音を背に、扉へ向かう。", "I head for the door, leaving the footsteps behind."))] },
    { id: "door", title: t("開かない扉", "The stuck door"), narrative: [clues.door.initial], choices: [a("door-inspect", t("設備を調べる", "Inspect the equipment"), "door-inspect", t("近づいて、動く場所を見る。", "I look closely at the moving parts."), { problem: 'door', observation: 1 }), hint('door', 'door')], problem: "door" },
    { id: "door-inspect", title: t("見えた手掛かり", "A visible clue"), narrative: [clues.door.inspect], choices: [a("door-deeper", t("もう少し詳しく調べる", "Look more closely"), "door-cause", t("表示と部品を見比べる。", "I compare the labels and parts."), { problem: 'door', observation: 2 }), hint('door', 'door-inspect'), a("door-controls", t("操作盤を見る", "Look at the controls"), "door-cause", t("原因を確かめながら盤を見る。", "I check the cause as I look at the panel."), { problem: 'door', observation: 2 })], problem: "door" },
    { id: "valve", title: t("動かないバルブ", "The stuck valve"), narrative: [clues.valve.initial], choices: [a("valve-inspect", t("点検カバーを開ける", "Open the inspection cover"), "valve-inspect", t("近づいて、動く場所を見る。", "I look closely at the moving parts."), { problem: 'valve', observation: 1 }), hint('valve', 'valve')], problem: "valve" },
    { id: "valve-inspect", title: t("見えた手掛かり", "A visible clue"), narrative: [clues.valve.inspect], choices: [a("valve-deeper", t("もう少し詳しく調べる", "Look more closely"), "valve-cause", t("表示と部品を見比べる。", "I compare the labels and parts."), { problem: 'valve', observation: 2 }), hint('valve', 'valve-inspect'), a("valve-equipment", t("周りの設備を見る", "Check nearby equipment"), "valve-cause", t("棚へ目を向ける。", "I look at the shelf."), { problem: 'valve', observation: 2 })], problem: "valve" },
    { id: "power", title: t("落ちる電源", "The tripping power"), narrative: [clues.power.initial], choices: [a("power-inspect", t("設備を調べる", "Inspect the equipment"), "power-inspect", t("近づいて、動く場所を見る。", "I look closely at the moving parts."), { problem: 'power', observation: 1 }), hint('power', 'power')], problem: "power" },
    { id: "power-inspect", title: t("見えた手掛かり", "A visible clue"), narrative: [clues.power.inspect], choices: [a("power-deeper", t("もう少し詳しく調べる", "Look more closely"), "power-cause", t("表示と部品を見比べる。", "I compare the labels and parts."), { problem: 'power', observation: 2 }), hint('power', 'power-inspect'), a("power-controls", t("操作盤を見る", "Look at the controls"), "power-cause", t("原因を確かめながら盤を見る。", "I check the cause as I look at the panel."), { problem: 'power', observation: 2 })], problem: "power" },
    { id: "door-cause", title: t("押し戻す空気", "Air pushing back"), narrative: [clues.door.deeper, t("「壊れた扉じゃなくて、押し合いか」", "\u201cSo it is a pushing contest, not a broken door.\u201d")], choices: [a("equalize", t("均圧を操作する", "Use EQUALIZE"), "door-result", t("空気が流れ、左右の表示が同じになる。扉はまだ閉じている。押し戻す矢印は同じ大きさになった。", "Air flows. Both labels match. The door is still closed. The opposing arrows now have the same size."), { problem: 'door', resolution: 'changed' }), a("door-force", t("もう一度開閉ボタンを押す", "Press OPEN again"), "door-cause", t("モーターは動くが扉は止まる。左右の圧力は違うままだ。「ボタンに八つ当たりしても、だめか」", "The motor runs, but the door stops. The pressures still differ. \u201cBlaming the button did not help.\u201d")), hint('door', 'door-cause')], problem: "door" },
    { id: "door-result", title: t("そろった表示", "Matching labels"), narrative: [t("左右の空気圧は同じ。モーターの故障灯は消えたままだ。", "Both air pressures match. The motor fault lamp is still off.")], choices: [a("door-open", t("開閉ボタンを押す", "Press OPEN"), "valve", t("扉が最後まで開く。圧力をそろえたら、同じモーターで動いた。「よし。押し合いは終了！」", "The door opens fully. With matching pressures, the same motor works. \u201cGood. Contest over!\u201d"), { problem: 'door', resolution: 'resolved' })], problem: "door" },
    { id: "valve-cause", title: t("氷と手元の設備", "Ice and nearby equipment"), narrative: [clues.valve.deeper, equipment.heater, equipment.tools], choices: [a("valve-heat", t("点検ヒーターを軸に当てる", "Put the heater on the shaft"), "valve-warm", t("白い氷が水滴に変わる。軸と枠の間が空いた。レバーはまだ押していない。「小さい太陽、助かったよ」", "White ice turns into drops of water. The space around the shaft is clear. I have not pushed the lever yet. \u201cThanks, little sun.\u201d"), { problem: 'valve', resolution: 'changed' }), a("valve-force", t("工具でレバーを回す", "Turn the lever with tools"), "valve-cause", t("金属がきしむ。軸は氷に当たって止まり、氷もそのままだ。「力の問題じゃないな」\n\nAI：ようやく工具にも同意してもらえましたね。", "Metal creaks. The shaft hits the ice and stops. The ice remains. \u201cSo strength is not the problem.\u201d\n\nAI: The tools seem to agree at last.")), hint('valve', 'valve-cause')], problem: "valve" },
    { id: "valve-warm", title: t("氷の消えた軸", "The ice-free shaft"), narrative: [t("軸は水滴でぬれている。突起の前に氷はない。", "Water dots the shaft. No ice remains in front of the ridge.")], choices: [a("valve-turn", t("レバーを押す", "Push the lever"), "valve-result", t("今度はレバーが最後まで動いた。管に空気が流れる。氷をなくしたら、同じ軸が回った。", "This time the lever moves all the way. Air flows through the pipe. Removing the ice let the same shaft turn."), { problem: 'valve', resolution: 'resolved' })], problem: "valve" },
    { id: "valve-result", title: t("流れた空気", "Air flowing again"), narrative: [t("氷は戻らず、バルブは開いたままだ。「腕力より、温かさか」\n\nAI：工具との口論も終わりました。", "The ice stays gone and the valve stays open. \u201cWarmth beats muscles.\u201d\n\nAI: Your argument with the tools is settled.")], choices: [a("to-power", t("帰還設備へ進む", "Go to the return equipment"), "power", t("船のランプが見える。ほっとした途端、電気が切れた。", "The ship\u2019s lamp comes into view. Just as I relax, the power cuts out."))], problem: "valve" },
    { id: "power-cause", title: t("同時に使いすぎ", "Too much at once"), narrative: [clues.power.deeper, t("「船の空気は欲しい。空っぽのリフトは……急がなくていい」", "\u201cI need air in the ship. The empty lift can wait.\u201d")], choices: [a("power-stop", t("貨物リフトを止めて再起動する", "Stop the cargo lift and restart"), "power-result", t("リフトは止まる。空気充填機だけが動き、針は上限より下に収まる。ブレーカーは落ちない。空のリフトは使えないが、船の空気は満たされた。", "The lift stops. Only the air pump runs. The meter stays below the limit and the breaker holds. The empty lift is unavailable, but the cabin fills with air."), { problem: 'power', resolution: 'resolved' }), a("power-order", t("二台を順番運転にする", "Run the machines in order"), "power-result", t("リフトが終わってから空気充填機が動く。少し待つが、針は上限を越えない。ブレーカーも落ちず、両方の作業が終わった。", "The lift finishes before the air pump starts. I wait a little, but the meter never crosses the limit. The breaker holds and both jobs finish."), { problem: 'power', resolution: 'resolved' }), a("power-retry", t("二台を同時に再起動する", "Restart both together"), "power-cause", t("針がまた上限を越え、OVERLOADで電気が切れる。故障灯は消えたまま。二台同時という条件は変わっていない。「再起動は魔法じゃないか」", "The needle crosses the limit again. OVERLOAD cuts the power. The fault lamp is still off. Both machines were still running together. \u201cRestarting is not magic.\u201d")), hint('power', 'power-cause')], problem: "power" },
    { id: "power-result", title: t("切れない電源", "Power that stays on"), narrative: [t("電気はついたままだ。同時に使う量を減らしたら、同じ電源で動いた。船内の空気ランプは緑。", "The power stays on. Reducing what runs at once lets the same supply work. The cabin air lamp is green.")], choices: [a("leave", t("帰還船に乗る", "Board the return ship"), "clear", t("ロボットの音を遠くに置いて、船の扉を閉める。", "I close the ship\u2019s door, leaving the robot\u2019s footsteps far behind."))], problem: "power" },
    { id: "clear", title: t("CLEAR", "CLEAR"), narrative: [t("基地が窓の下へ遠ざかる。肩の力が抜けた。「壊れていると思ったもの、案外壊れてなかったね」\n\nAI：観察の効果です。ボタンへの八つ当たりよりは。", "The base shrinks below the window. My shoulders relax. \u201cThings I thought were broken were not so broken after all.\u201d\n\nAI: Observation helps. More than blaming buttons.")], choices: [], ending: 'clear' },
];
export const scenes = Object.fromEntries(list.map(scene => [scene.id, scene])) as Record<SceneId, Scene>;
