import { text as T } from './i18n.ts'
import type { Scene, SceneId, Choice, KnowledgeId } from './model.ts'
export const knowledge: Record<KnowledgeId, ReturnType<typeof T>> = {
  'light-response': T('強い白い光でロボットの走査が止まった。暗くしても走査は続いた。', 'Strong white light stopped the robot’s scan. The scan continued in darkness.'),
  'arm-traces': T('ロボットがアームを回すと、壁に二本の黒いこすれた跡が残る。', 'When the robot swings its arm, it leaves two black scrapes on the wall.'),
  'independent-power': T('古い整備用の装置には別の電源がある。基地の主電源が切れても青い表示は消えない。', 'The old service equipment has its own power. Its blue indicators stay lit when the base’s main power goes off.'),
  'launch-order': T('帰還船は「圧力固定 → 点火」。逆にすると空気が外へ抜ける。', 'The return ship needs pressure lock before ignition. The reverse order lets its air out.'),
}
const C = (id: string, ja: string, en: string, next: SceneId, resultJa: string, resultEn: string, rest: Partial<Choice> = {}): Choice => ({ id, label: T(ja, en), next, result: T(resultJa, resultEn), ...rest })
const noisy = (next: SceneId): Choice['routes'] => [{ when: { threatMin: 2 }, next: 'encounter' }, { when: {}, next }]
export const scenes: Record<SceneId, Scene> = {
  wake: {
    id: 'wake', title: T('目覚めた場所', 'Where I wake'),
    narrative: [T('天井の隙間から灰色の粉が降ってくる。スーツの中では、いつも通りに息ができる。「まいったな。目覚ましにしては派手すぎる」', 'Grey dust falls from a gap in the ceiling. I can still breathe normally inside my suit. “Well, that is one way to wake me up.”'), T('壁には二本の黒いこすれた跡。扉の外で金属音が三度鳴り、ぴたりと止まる。思わず息をひそめる。', 'Two black scrapes mark the wall. Metal knocks three times outside the door, then stops dead. I catch myself holding my breath.'), T('AI：基地は大きく壊れています。帰還船で脱出してください。この扉はまだ空気を保っています。目覚ましの苦情は、その後で。', 'AI: The base is badly damaged. You need to escape in the return ship. This door still holds air. Alarm complaints can wait.')],
    choices: [C('check-kit', '足元の救急ケースを開く', 'Open the emergency case at my feet', 'kit', '留め具を外すと、ケースの中は乾いている。何か使える物があってくれ。', 'I open the catches. The case is dry inside. Please let there be something useful.'), C('leave-case', 'ケースを残し、扉に耳を寄せる', 'Leave the case and listen at the door', 'door', 'ケースを残して扉へ近づく。身軽なのはいいが、少し心細い。', 'I leave the case and move toward the door. Less to carry, but I feel a little less safe.')],
  },
  kit: {
    id: 'kit', title: T('一回分の備え', 'One reserve'),
    narrative: [T('ケースの中にはライトと小さな酸素容器がある。容器の帯は絡まっていて、ほどくには時間がかかる。', 'The case holds a light and a small oxygen flask. The tangled flask strap will take time to undo.'), T('扉の向こうで、また金属音が三度鳴る。さっきより近い。「急かさなくても聞こえてるよ」', 'Three metallic knocks come from beyond the door again. Closer this time. “I hear you. No need to rush me.”'), T('AI：予備酸素は一回分です。作業が長引けば、その間もスーツの空気を使います。荷造りは手短に。', 'AI: The flask holds one refill. A long job uses suit air while you work. Keep the packing brief.')],
    choices: [C('take-both', '固定帯をほどき、ライトと予備酸素を持つ', 'Untangle the strap; take light and oxygen', 'door', '帯をほどく間も、ファンが空気を送り続ける。やっと二つをスーツに留める。「手強い帯だったな」', 'The fan feeds air while I undo the strap. At last, I secure both to my suit. “Quite a fight for a strap.”', { effect: { gain: ['light', 'flask'], oxygen: 1, threat: 1 } }), C('take-light', 'すぐ取れるライトだけ持つ', 'Take just the loose light', 'door', 'ライトを抜き取り、容器は残す。「悪いな。急いでるんだ」', 'I take the light and leave the flask. “Sorry. In a hurry.”', { effect: { gain: ['light'] } })],
  },
  door: {
    id: 'door', title: T('音の間隔', 'Between the sounds'),
    narrative: [T('扉の隙間を細い影が横切る。床をなぞる赤い光は、記録端末の白い画面の前で引き返す。', 'A thin shadow crosses the door gap. Red light sweeps the floor, then turns back at a record terminal’s white screen.'), T('金属音が三度鳴って止まる。隙間から、点滅する端末と青い整備用の表示が見える。背筋が冷える。', 'Metal knocks three times and stops. Through the gap, I see the terminal flicker and a blue service indicator. A chill runs down my back.'), T('AI：動いている機械を検知しました。今、扉を大きく開けるのは危険です。挨拶は控えましょう。', 'AI: A moving machine is detected. Opening the door wide now is dangerous. Let us skip the introductions.')],
    choices: [C('read-terminal', '赤い光が引いたら、端末へ手を伸ばす', 'Reach the terminal when the red light pulls back', 'records', '光が引いた隙に、体を低くして滑り込む。心臓がうるさい。', 'I slip through low as the light pulls back. My heartbeat seems far too loud.', { effect: { threat: 1 } }), C('service-hatch', '青い表示の下の点検蓋をそっと外す', 'Gently lift the hatch below the blue light', 'service', '蓋は手で外れた。中のファンは回り続けている。音が変わらず、ほっとする。', 'The hatch lifts by hand. The fan inside keeps running. Its steady sound is a relief.'), C('force-door', '危険を承知で扉を押し開ける', 'Accept the danger and force the door open', 'encounter', '扉が床をこする。赤い光が胸で止まり、後悔が一気に押し寄せる。', 'The door scrapes the floor. Red light stops on my chest, and regret hits me all at once.', { effect: { threat: 2 } })],
  },
  records: {
    id: 'records', title: T('最後の記録', 'The last record'),
    narrative: [T('画面には整備映像と帰還船の操作記録。映像の初めで、白い作業灯を向けられたロボットが走査を止める。', 'The screen shows maintenance footage and a ship log. The footage begins with a white work lamp stopping the robot’s scan.'), T('続きはなかなか読み込まれない。端末のファンの音だけが大きくなる。「今だけは、のんびりしないでほしいな」', 'The rest is slow to load. The terminal fan just gets louder. “Any time now would be lovely.”'), T('AI：全記録を見るには時間がかかります。画面の要約なら、すぐ読めます。端末を励ましても速度は変わりません。', 'AI: The full recording takes time. The summary on screen is a quick read. Encouraging the terminal will not help.')],
    choices: [C('full-record', '追跡映像と発進記録を最後まで見る', 'Watch the pursuit footage and read the full launch log', 'playback', '最後まで見る間、ファンの音に金属音が重なる。画面から目を離したい。でも続きを知りたい。', 'Metal sounds join the fan as I watch to the end. I want to look away, but I need to know the rest.', { effect: { learn: ['light-response', 'arm-traces', 'launch-order'], oxygen: 1, threat: 1 } }), C('summary', '白い作業灯の要約だけ読み、離れる', 'Read just the white-lamp summary and leave', 'seal', '要約には「強い白い光で走査が止まる。暗くしても効果なし」。短いが、覚えておこう。', 'The summary says, “Strong white light stops the scan. Darkness does not help.” Short, but I had better remember it.', { effect: { learn: ['light-response'] } }), C('skip-record', '記録を読まず、端末の音から離れる', 'Leave the noisy terminal without reading', 'seal', '点滅する画面に背を向ける。続きは気になるが、今は離れたい。', 'I turn away from the blinking screen. I want answers, but right now I want some distance more.', { effect: { threat: -1 } })],
  },
  playback: {
    id: 'playback', title: T('黒い跡の正体', 'What made the marks'),
    narrative: [T('映像のロボットが向きを変えると、アームが壁をこする。二本の黒い筋が残る。目覚めた部屋にもあった跡だ。ぞっとする。', 'The robot turns in the footage, scraping its arm along the wall. It leaves two black lines. My stomach tightens. Those marks were in the room where I woke.'), T('発進記録には「圧力固定 → 点火」。先に点火した試験では、船の空気が外へ抜けている。順番だけは間違えたくない。', 'The launch log reads “Pressure lock → Ignition.” In a test with ignition first, the ship’s air escapes. That is one order I want to get right.'), T('机の下には、音で気を引くデコイ。試験ランプが点いていて、抜くと音が鳴りそうだ。', 'A decoy under the desk makes noise to draw attention. Its test light is on. Pulling it free looks likely to make noise.')],
    choices: [C('take-decoy', '音を承知でデコイを引き抜く', 'Pull the decoy free despite the noise', 'seal', '試験音が三度鳴る。デコイを握って離れる。「静かなお土産はないのかよ」', 'Three test knocks ring out. I grab the decoy and leave. “No quiet souvenirs, then?”', { effect: { gain: ['decoy'], threat: 1 }, routes: noisy('seal') }), C('leave-decoy', 'デコイを残し、静かに離れる', 'Leave the decoy and withdraw quietly', 'seal', '机には触れず、ファンから離れる。これ以上、音を増やしたくない。', 'I leave the desk alone and move away from the fan. I have heard enough noise for now.', { effect: { threat: -1 } })],
  },
  service: {
    id: 'service', title: T('消えない青', 'Blue that stays lit'),
    narrative: [T('頭上の非常灯がいっせいに消える。でも、点検蓋の中は青く光り、ファンも止まらない。少しほっとする。', 'The lamps overhead go dark. But the blue light and fan inside the hatch stay on. A small relief.'), T('金属の札には「旧整備系統・独立電源」。奥には工具台と細い空気の配管が見える。「まだ働いてる場所があるんだな」', 'A metal plate reads “Old service system — independent power.” Beyond it are a tool bench and a thin air pipe. “So something here still works.”'), T('AI：主電源とは別の電源です。基地全体は直せません。この箱にしては大仕事ですから。', 'AI: It has its own power supply. It cannot repair the whole base. A big job for one box.')],
    choices: [C('inspect-bench', '青い配管に沿って工具台を調べる', 'Follow the blue line and inspect the bench', 'workbench', '青い表示は別の電源で動いている。札の内容を覚え、工具台へ近づく。', 'The blue indicator runs on separate power. I remember what the plate says and move toward the bench.', { effect: { learn: ['independent-power'] } }), C('crawl-through', '立ち止まらず、狭い隙間を抜ける', 'Keep moving through the narrow gap', 'seal', '狭い縁で左腕を打つ。声をこらえて抜けるが、腕に力が入らない。', 'My left arm hits the narrow rim. I choke back a cry and get through, but the arm feels weak.', { effect: { body: 'injured' } })],
  },
  workbench: {
    id: 'workbench', title: T('外すか、引くか', 'Unfasten or pull'),
    narrative: [T('工具を留めた金属の帯には、何本もネジがある。指で回せるが、裏の試験札はまだ読めない。', 'A metal strap holds the tools, with several screws I can turn by hand. A test tag is hidden behind it.'), T('隣の「音の試験」の箱にはデコイが差してある。スイッチが入っていて、抜けば音が出そうだ。', 'The “Sound test” box beside it holds a decoy. Its switch is on. Pulling it out looks likely to make noise.'), T('配管から冷たい空気が漏れている。ここで手間取れば、スーツの空気も減る。早く決めなきゃ、と気ばかり焦る。', 'Cold air leaks from the pipe. Taking too long here will use up suit air too. I feel rushed to make a choice.')],
    choices: [C('unscrew-tools', 'ネジを外して試験札を読み、工具を持つ', 'Undo the screws, read the test tag and take the tools', 'seal', '帯を外すと札が読める。「強い白い光で走査が止まる。暗くしても効果なし」。工具が鳴らないように包む。', 'With the strap off, I can read the tag: “Strong white light stops the scan. Darkness does not help.” I wrap the tools so they will not clink.', { effect: { gain: ['tools'], oxygen: 1, learn: ['light-response'] } }), C('pull-decoy', '音を承知で試験箱のデコイを抜く', 'Pull the decoy from the test box despite the noise', 'seal', '試験音が響いて、肩が跳ねる。箱は残し、デコイだけ持つ。', 'The test sound rings out, making me jump. I leave the box and take only the decoy.', { effect: { gain: ['decoy'], threat: 1 }, routes: noisy('seal') }), C('leave-bench', '道具に触れず、空気漏れから離れる', 'Leave the tools and move away from the leak', 'seal', '工具台を離れる。青い光が背中に回ると、頼れる物を置いてきた気がする。', 'I leave the bench. As the blue glow falls behind me, I feel I have left something useful behind too.')],
  },
  seal: {
    id: 'seal', title: T('袖口の振動', 'A vibration at the cuff'),
    narrative: [T('袖口が震え、シューッと空気が漏れている。布の下の締め輪がずれている。「今度はスーツか。順番待ちしてくれよ」', 'My cuff shakes, leaking air with a hiss. The ring under the fabric has slipped. “Now the suit? Get in line.”'), T('先の扉には帰還船への案内灯。輪を確かめる間も遠くで金属音が鳴り、焦ってくる。', 'A light on the door ahead points toward the ship. Distant metal sounds make me hurry as I check the ring.'), T('AI：小さな空気漏れです。押さえれば歩けますが、走ると酸素が減ります。修理には時間が必要です。順番待ちはしませんよ。', 'AI: A small air leak. Hold it to walk; running costs oxygen. Repairs take time. Leaks do not wait in line.')],
    additions: [{ when: { body: 'injured' }, text: T('左腕で輪を押すと、ずきりと痛む。くやしいけれど、素手で直す力は残っていない。', 'Pain shoots through my left arm when I press the ring. I hate it, but I do not have the grip to fix this by hand.') }],
    choices: [C('tool-seal', '工具で締め輪を直す', 'Correct the ring with tools', 'marks', '工具で輪を少しずつ戻す。空気の音が止まり、ようやく手の力を抜く。', 'I ease the ring back with a tool. The hiss stops, and I finally loosen my grip.', { when: { items: ['tools'] }, effect: { oxygen: 1, once: 'sealed' } }), C('hand-seal', '腕に力を込め、締め輪を戻す', 'Force the ring back by hand', 'marks', '輪は戻った。でも左腕に痛みが走る。「直ったのは、スーツだけか」', 'The ring goes back into place, but pain shoots through my left arm. “Only the suit got fixed, then.”', { when: { body: 'normal' }, effect: { body: 'injured', once: 'sealed' } }), C('hold-seal', '袖口を押さえ、立ち止まらず進む', 'Hold the cuff and keep walking', 'marks', '袖口を押さえると、音が弱まる。走りたい気持ちをこらえ、歩いて進む。', 'Holding the cuff quiets the hiss. I fight the urge to run and keep walking.')],
  },
  marks: {
    id: 'marks', title: T('二本の黒い筋', 'Two black lines'),
    narrative: [T('扉の右端に、二本の黒いこすれた跡がある。奥の床を赤い光がゆっくり横切る。またあの音がしそうで、足が止まる。', 'Two black scrapes mark the right edge of the door. Red light moves slowly across the floor beyond. I stop, dreading those knocks again.'), T('左には低い配管の陰がある。床の金属板は浮いていて、踏めば大きな音がしそうだ。', 'Low pipes cast a shadow on the left. A loose metal floor plate looks ready to clang if I step on it.')],
    additions: [{ when: { knowledge: ['arm-traces'] }, text: T('あの映像と同じ跡だ。右側でアームが向きを変えたんだ。ぞっとするが、配管の陰ならアームより低い。', 'The marks match the footage. The arm turned on the right. That chills me, but the pipe shadow is lower than the arm.') }, { when: { knowledge: ['light-response'], items: ['light'] }, text: T('赤い光は走査だ。白い作業灯で止まったのを思い出す。少し落ち着いて、ライトを強くするスイッチに指を置く。', 'The red light is a scan. I remember it stopping under the white work lamp. A little calmer, I put my finger on the light’s strong-beam switch.') }],
    choices: [C('trace-shadow', '跡からアームの高さを読み、配管の陰へ', 'Judge the arm’s height from the marks; use the pipe shadow', 'relay', '低くかがみ、赤い光をやり過ごす。あの怖い映像が、今は助けになっている。', 'I crouch low and let the red light pass. That frightening footage is helping me now.', { when: { knowledge: ['arm-traces'] }, effect: { threat: -1 } }), C('flood-scan', '走査に強い白い光を向ける', 'Aim a strong white beam at the scan', 'relay', '強い白い光で赤い走査が止まる。その隙に扉を抜ける。「効いた。助かった」', 'The strong white beam stops the red scan. I slip through the door. “It worked. Thank goodness.”', { when: { knowledge: ['light-response'], items: ['light'] }, effect: { threat: -1 } }), C('wait-scan', '赤い光が遠のくまで身を伏せる', 'Lie low until the red light moves away', 'relay', '光が引くまで待つ。立ち上がると、スーツのファンがやけにうるさい。待った分の空気は戻らない。', 'I wait for the light to move away. When I stand, my suit fan seems too loud. I will not get that air back.', { effect: { oxygen: 1, threat: -1 } }), C('step-plate', '待たずに金属板を踏み越える', 'Cross the loose plate without waiting', 'relay', '足元で板がガンと鳴る。しまった、と思っても、音は止められない。', 'The plate clangs under my foot. I wince, but I cannot take the sound back.', { effect: { threat: 1 }, routes: noisy('relay') })],
  },
  relay: {
    id: 'relay', title: T('止まったリフト', 'The stopped lift'),
    narrative: [T('帰還船へ上がるリフトは、灯りが消えている。隣の古い操作箱だけが青く光る。「休むなら、私を運んでからにしてくれ」', 'The lift up to the ship has no lights. Only an old control box beside it glows blue. “Take your break after you carry me, please.”'), T('手動レバーは重いばねで押さえられている。主電源をつなぎ直すボタンには「試験警報」の文字がある。', 'A heavy spring holds the manual lever in place. The button to reconnect main power is marked “Test alarm.”')],
    additions: [{ when: { oxygenMin: 2 }, text: T('空気が薄く、息を吸っても苦しい。警告が点滅している。もう長い作業はできない。冗談を言う息も惜しい。', 'The air is thin, and breathing hurts. A warning blinks. I cannot afford another long job. Even a joke takes too much breath.') }, { when: { knowledge: ['independent-power'] }, text: T('点検蓋の中と同じ青だ。あの独立電源なら、主電源を入れずにリフトを動かせる。まだ手はある。', 'The blue matches the light inside the hatch. That independent supply can run the lift without turning on main power. I still have a way through.') }, { when: { threatMax: 0 }, text: T('遠くで何かが動いている。次の音まで、まだ間がある。肩の力が少し抜ける。', 'Something moves far away. There is still time between the sounds. My shoulders ease a little.') }, { when: { threatMin: 1, threatMax: 1 }, text: T('金属音が何度も近づいてくる。レバーに伸ばした手を止める。まだ来るなよ、と耳を澄ます。', 'Metal sounds draw closer again and again. I stop reaching for the lever and listen. Please, not yet.') }, { when: { threatMin: 2 }, text: T('扉の向こうでモーターの音が止まった。赤い光が隙間をなぞる。すぐそこだ。つばを飲むのも怖い。', 'A motor stops beyond the door. Red light traces the gap. Right there. I am almost afraid to swallow.') }, { when: { oxygenMax: 0 }, text: T('スーツは同じ速さで空気を送ってくれる。ひと息ついて、手元を確かめる。', 'The suit keeps sending air at a steady pace. I take a breath and check what is in front of me.') }, { when: { oxygenMin: 1, oxygenMax: 1 }, text: T('リフトは静かなのに、スーツのファンがやけにうるさい。空気が減っていると思うと、急ぎたくなる。', 'The lift is silent, but my suit fan seems much too loud. Knowing the air is running low makes me want to hurry.') }],
    choices: [C('blue-power', '青い操作箱で独立電源をつなぐ', 'Connect the independent supply at the blue box', 'airlock', '青い表示が明るくなり、リフトが静かに上がる。思わず口元がゆるむ。', 'The blue indicators brighten, and the lift rises quietly. I cannot help a small smile.', { when: { knowledge: ['independent-power'] } }), C('manual-lift', '重いレバーを手で押し切る', 'Push the heavy lever through by hand', 'airlock', 'ばねを押し切ると、腕に痛みが走る。リフトは動いた。「運賃は腕一本分か」', 'I push past the spring, and pain shoots through my arm. The lift moves. “Expensive ride.”', { when: { body: 'normal' }, effect: { body: 'injured' } }), C('tool-lift', '工具をてこにしてレバーを動かす', 'Use a tool to lever the handle', 'airlock', '工具を挟み、ゆっくりレバーを押す。何度も息をするうちに、リフトが動く。やっとだ。', 'I brace a tool and push the lever slowly. Several breaths later, the lift moves. At last.', { when: { items: ['tools'] }, effect: { oxygen: 1 } }), C('alarm-power', '警報を承知で主電源を再接続する', 'Reconnect main power despite the alarm', 'airlock', '警報が鳴り、リフトに灯りが戻る。動いたのはうれしいが、音が大きすぎる。', 'The alarm rings, and the lift lights come back. I am glad it works, but I wish it were quieter.', { effect: { threat: 1 }, routes: noisy('airlock') }), C('wait-relay', '物陰で機械音が離れるのを待つ', 'Wait in cover for the machine to move away', 'relay', '三度の音が遠くへ移る。ほっとする間にも、空気は減っていく。', 'The triple knock moves farther away. Even while I feel relieved, my air keeps running low.', { when: { unused: 'relay-wait' }, effect: { threat: -1, oxygen: 1, once: 'relay-wait' } })],
  },
  encounter: {
    id: 'encounter', title: T('走査光の下で', 'Under the scan'),
    narrative: [T('赤い光が私の胸で止まる。ロボットのアームが扉をこすり、二本の黒い筋を引く。床がきしみ、足がすくむ。', 'Red light stops on my chest. The robot’s arm scrapes two black lines across the door. The floor creaks, and my legs freeze.'), T('低い機材棚の下に隙間がある。白い非常灯のスイッチには、工具が必要なネジ付きカバー。「歓迎が熱すぎるよ」', 'There is a gap under a low equipment shelf. The white emergency-lamp switch has a cover screwed down; I need a tool. “Quite a welcome.”'), T('AI：すぐに逃げてください。走ると空気を使います。暗くしても走査は止まりません。歓迎なら、距離が近すぎます。', 'AI: Get away now. Running uses air. Darkness will not stop the scan. For a welcome, this is much too close.')],
    choices: [C('use-decoy', 'デコイを投げ、音と逆へ逃げる', 'Throw the decoy and slip away from the sound', 'refuge', '三度の音へ赤い光が向く。焼けたデコイを残して逃げる。「そっちだ。私じゃない」', 'The red light turns toward the triple knock. I escape, leaving the burned-out decoy. “That way. Not me.”', { when: { items: ['decoy'] }, effect: { consume: ['decoy'], threat: -2 } }), C('emergency-light', 'カバーを外し、白い非常灯をつける', 'Remove the cover and turn on the white emergency lamp', 'refuge', '工具でカバーを外す。白い光で走査が止まり、震える足で離れる。', 'I remove the cover with a tool. The white light stops the scan, and I back away on shaking legs.', { when: { items: ['tools'], knowledge: ['light-response'] }, effect: { oxygen: 1, threat: -1 } }), C('use-light', 'ライトを強い白い光に切り替える', 'Switch the light to a strong white beam', 'refuge', '白い光がアームを照らす。走査が止まった隙に逃げる。今は軽口も出ない。', 'White light catches the arm. I escape while the scan is stopped. No jokes come to me now.', { when: { items: ['light'], knowledge: ['light-response'] }, effect: { threat: -1 } }), C('run', '腕を痛める覚悟で、棚の下へ飛び込む', 'Dive under the shelf, hurting my arm', 'refuge', '左腕を棚にぶつけ、息が乱れる。痛い。でも、アームはここまで届かない。', 'My left arm hits the shelf, and my breathing breaks. It hurts. But the arm cannot reach me here.', { when: { body: 'normal', oxygenMax: 1 }, effect: { body: 'injured', oxygen: 1, threat: -1 }, routes: [{ when: { unused: 'sealed' }, next: 'refuge', effect: { oxygen: 2 }, result: T('棚へ飛び込むと、袖口が開いた。アームは届かないが、空気が一気に抜ける。息を吸っても足りない。', 'I dive under the shelf, and my cuff opens. The arm cannot reach me, but air rushes out. I cannot get enough breath.') }] }), C('dark-hide', '照明を消し、その場でじっとする', 'Turn off the light and stay still', 'robot-over', '暗くしても赤い光は消えない。アームが視界をふさぐ。間違えた、と体がこわばる。', 'The red light stays even in the dark. The arm fills my view. I freeze as I realise my mistake.')],
  },
  refuge: {
    id: 'refuge', title: T('届かない隙間', 'Out of reach'),
    narrative: [T('棚の向こうで金属音が三度鳴り、遠ざかる。やっと息を吐くと、低い点検口の先に帰還船の気密室が見える。', 'Metal knocks three times beyond the shelf, then moves away. I finally let out a breath and spot the ship’s airlock through a low service opening.'), T('狭くて立てないが、這って抜けられそうだ。ここで待つより、息を整えて進もう。', 'There is no room to stand, but I can crawl through. Better to steady my breathing and move than wait here.')],
    additions: [{ when: { body: 'injured' }, text: T('左腕が痛む。肘をつかず、肩で体を支える。今はこの腕をかばうしかない。', 'My left arm hurts. I use my shoulder to support myself, keeping off the elbow. I have to protect that arm for now.') }],
    choices: [C('close-refuge', '時間をかけて点検蓋を閉め、音を遮る', 'Take time to close the hatch and muffle the noise', 'airlock', '蓋をそっと閉める。何度か息をすると音が弱まり、肩から力が抜ける。', 'I close the hatch gently. After several breaths, the sound fades and my shoulders relax.', { effect: { oxygen: 1, threat: -1 } }), C('crawl-out', '呼吸を整え、点検口をくぐる', 'Steady my breathing and crawl through', 'airlock', '肩を低くして隙間を抜ける。気密室の灯りが見え、ようやく顔を上げる。', 'I lower my shoulder and squeeze through. The airlock lights come into view, and I finally lift my head.'), C('refuge-refill', '予備酸素を使ってから点検口をくぐる', 'Refill my oxygen before crawling through', 'airlock', '容器をつなぐと、息が楽になる。落ち着いて点検口を抜ける。', 'I connect the flask, and breathing gets easier. Calmer now, I crawl through the opening.', { when: { items: ['flask'] }, effect: { refill: true, consume: ['flask'] } })],
  },
  airlock: {
    id: 'airlock', title: T('空気を守る扉', 'A door that holds air'),
    narrative: [T('ガラスの向こうに帰還船の入口が見える。扉を閉めるボタンの横には「自動均圧」と「手動弁」の表示がある。', 'The ship entrance is just beyond the glass. Beside the door-close button are labels for “Automatic equalisation” and “Manual valve.”'), T('自動均圧のランプはゆっくり点滅している。手動弁は細く、手袋ではつかめない。あと少しなのに、じれったい。', 'The automatic lamp blinks slowly. The manual valve is too thin to grip with gloves. So close, and still stuck waiting.'), T('AI：自動均圧は、空気の圧力がそろうまで待ちます。扉が開いたまま非常開放すると、呼吸用の空気を失います。近道にも請求は来ます。', 'AI: Automatic equalisation means waiting for the air pressures to match. Emergency release with the door open costs breathing air. Shortcuts still have a price.')],
    additions: [{ when: { oxygenMin: 2 }, text: T('吸っても空気が足りず、胸が苦しい。ここでさらに待てば、最後の空気を使い切る。焦るなと言われても、無理だ。', 'I breathe in, but it is not enough. My chest aches. Waiting here will use the last air. Staying calm is a lot to ask.') }, { when: { oxygenMax: 0 }, text: T('息でガラスが曇り、すぐ晴れる。まだ落ち着いて待てる。それだけでもありがたい。', 'My breath fogs the glass, then clears. I still have enough air to wait calmly. I am grateful for that much.') }, { when: { oxygenMin: 1, oxygenMax: 1 }, text: T('息を吸うたびにファンが長く回る。空気が減っている。点滅するランプに、つい「早く」とつぶやく。', 'The fan runs longer with each breath. My air is running low. I catch myself whispering “Hurry” to the blinking lamp.') }],
    choices: [C('manual-valve', '工具で手動弁を回し、空気を閉じ込める', 'Turn the manual valve with tools and trap the air', 'ship', '工具で弁を回す。空気の流れが止まるのを確かめ、そっと扉を開く。', 'I turn the valve with a tool. Once the airflow stops, I ease the door open.', { when: { items: ['tools'] }, effect: { threat: 1 }, routes: noisy('ship') }), C('equalise', '扉を閉め、自動均圧を待つ', 'Close the door and wait for equalisation', 'ship', '扉が閉まる。息を重ね、ランプの点滅が止まるまで待つ。いつもより長く感じる。', 'The door closes. I keep breathing and wait until the lamp stops blinking. It feels longer than it should.', { effect: { oxygen: 1, threat: -1 } }), C('airlock-refill', '予備酸素を使い、余裕を作る', 'Use reserve oxygen to make time', 'airlock', '容器をつなぐと、吸える空気が戻る。空になった容器を見て、助かった、と息を吐く。', 'I connect the flask, and air returns. Looking at the empty flask, I let out a relieved breath.', { when: { items: ['flask'] }, effect: { consume: ['flask'], refill: true } }), C('vent-door', '空気を失う危険を承知で非常開放する', 'Use emergency release despite losing air', 'ship', '空気が扉へ吸い出される。スーツが短く警告を鳴らし、ひやりとする。', 'Air rushes toward the door. My suit gives a short warning, and I feel a jolt of fear.', { effect: { oxygen: 1, threat: 1 }, routes: noisy('ship') })],
  },
  ship: {
    id: 'ship', title: T('二つのスイッチ', 'Two switches'),
    narrative: [T('帰還船の座席に腰を下ろす。目の前には「圧力固定」と「点火」のスイッチ。「よし。ここまで来たぞ」', 'I sit down in the return ship. The switches in front of me read “Pressure lock” and “Ignition.” “All right. I made it this far.”'), T('透明なカバーの内側に、小さな手順票がある。カバーを外せば読める。最後に間違えたくない。', 'A small instruction card sits inside a clear cover. I must remove the cover to read it. No mistakes now.'), T('AI：帰還航路は設定済みです。圧力固定はまだです。お祝いは、あと二つのスイッチの後で。', 'AI: The course home is set. Pressure lock is not engaged yet. Two switches, then celebrations.')],
    additions: [{ when: { oxygenMin: 2 }, text: T('警告が点滅している。カバーを外して読む間も、空気を使う。船まで来たのに、と唇をかむ。', 'A warning blinks. Removing the cover and reading the card still uses air. I bite my lip. I have come all this way.') }, { when: { knowledge: ['launch-order'] }, text: T('端末で読んだ順番を思い出す。空気が抜けた試験と同じスイッチだ。覚えている。大丈夫。', 'I remember the order from the terminal. These are the same switches from the test that vented the air. I remember. I can do this.') }],
    choices: [C('known-launch', '記録の通り、圧力を固定してから点火する', 'Follow the record: lock pressure, then ignite', 'clear', '圧力固定の表示を確かめて、点火。座席が震える。「行け。今度こそ」', 'I check the pressure-lock light, then ignite. The seat shakes. “Go. This time, go.”', { when: { knowledge: ['launch-order'] } }), C('read-card', 'カバーを外し、手順票を読む', 'Remove the cover and read the procedure card', 'checklist', 'ファンの音を聞きながらカバーを外す。票には発進の順番が図で描いてある。これなら分かる。', 'I listen to the fan as I remove the cover. The card shows the launch order in a diagram. I can follow this.', { effect: { oxygen: 1, learn: ['launch-order'] }, routes: [{ when: { items: ['tools'] }, next: 'checklist', effect: { oxygen: 0 }, result: T('工具ですぐにカバーが外れる。票の発進順序が読めて、少しほっとする。', 'The tool gets the cover off at once. I can read the launch order, and I feel a little relief.') }] }), C('ignite-first', '空気排出の危険を承知で、先に点火する', 'Ignite first despite the risk of venting air', 'oxygen-over', '排気弁が開く。体を座席に留める前に、空気が抜けていく。「待ってくれ」と声が漏れる。', 'The vent valve opens. Air drains away before I can strap myself in. “Wait,” I hear myself say.')],
  },
  checklist: {
    id: 'checklist', title: T('固定、そして点火', 'Lock, then ignite'),
    narrative: [T('手順票には「圧力固定 → 点火」。逆にすると空気が抜ける、と赤枠で書いてある。震える指で順番を確かめる。', 'The card reads “Pressure lock → Ignition.” A red box warns that the reverse order lets the air out. I check the order with a shaking finger.'), T('窓には基地の非常灯が映っている。あと二つの操作で、あの灯りから離れられる。「さあ、帰ろう」', 'The base’s emergency lights reflect in the window. Two more steps to leave those lights behind. “Time to go home.”')],
    choices: [C('card-launch', '手順票の通りに圧力を固定し、点火する', 'Lock pressure and ignite as the card instructs', 'clear', '圧力固定の表示が点く。点火すると、窓の基地が下がっていく。握っていた手を、やっと開く。', 'The pressure-lock light comes on. I ignite, and the base sinks below the window. At last, I unclench my hand.'), C('flask-launch', '予備酸素を使い、呼吸を整えて発進する', 'Refill, steady my breath, then launch', 'clear', '予備酸素を使い、圧力を固定する。点火の振動が伝わる。今は落ち着いて息ができる。', 'I use the reserve oxygen and lock pressure. The vibration of ignition reaches me. Now I can breathe calmly.', { when: { items: ['flask'] }, effect: { consume: ['flask'], refill: true } })],
  },
  clear: { id: 'clear', title: T('EXIT SEQUENCE / GAME CLEAR', 'EXIT SEQUENCE / GAME CLEAR'), narrative: [T('月面の灯りが小さな点になっていく。船の空気を胸いっぱいに吸う。「ああ、もう一度吸える。最高だな」', 'The lights on the Moon shrink to a tiny point. I take a full breath of cabin air. “Another breath. Oh, that feels good.”'), T('AI：月面を離れました。地球への帰還航路に入ります。呼吸の感想なら、しばらく聞けます。', 'AI: We have left the Moon. Entering the course back to Earth. There is time for your review of breathing now.')], choices: [], ending: 'clear' },
  'robot-over': { id: 'robot-over', title: T('GAME OVER / 途切れた走査', 'GAME OVER / The final scan'), narrative: [T('赤い光で何も見えない。後ずさりしたいのに、もう逃げ場がない。スーツに金属音が響き、表示が消える。', 'Red light fills my view. I want to step back, but there is nowhere left to go. Metal strikes my suit, and the display goes dark.'), T('AI：退避できません。', 'AI: No escape is available.')], choices: [], ending: 'over' },
  'oxygen-over': { id: 'oxygen-over', title: T('GAME OVER / 最後の空気', 'GAME OVER / The last air'), narrative: [T('息を吸おうとしても、空気が来ない。もう一度、と願っても胸は苦しいままだ。視界の端で警告だけが点滅する。', 'I try to breathe, but no air comes. I wish for just one more breath, but my chest stays tight. Only the warning blinks at the edge of my view.'), T('AI：呼吸用の酸素が尽きました。', 'AI: The breathing oxygen is gone.')], choices: [], ending: 'over' },
}
